server:
  port: 8082
spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
  application:
    name: ${project.artifactId}
logging:
  pattern:
    console: '%boldWhite(%d) | %green([%t]) | [%highlight(%p)] %highlight(%c{1.}.%M\(%L\)): %highlight(%msg%n)'
    file: '%d [%t] %p %c{1.}.%M\(%L\)  %m%n'
  file:
    name: logs/${project.artifactId}.log
# Heimdall 参数配置
heimdall:
  security:
    session:
      session-name: HSessionId
      globalSessionTimeout: 301
      session-id-prefix: "heimdall:sessions:"
      active-session-cache-key: "heimdall:active-sessions:"
      active-user-cache-key: "heimdall:active-users:"
      renew: true
      ratio: 0.5
    scheduler:
      initialDelay: 30
      period: 30
    cookie:
      enabled: true
      name: ${heimdall.security.session.session-name}
      max-age: -1
      path: /
      http-only: true
      secure: false
      version: 0
    authorities-cached-key: "heimdall:authorities"
